### ISSUE TITLE
'MQTT' does not name a type

### ISSUE THREAD

**Issue by javiercviegas** [AdySan/HomeKitLight#1]
Hi Ady, first of all thanks for sharing i am starting with this awesome world and your work is really something to start at.

I am getting this error when verifying the code with arduino ide. What´s wrong? Might be a syntax issue with the new ide?

Thanks in advance

Javier

Arduino:1.6.9 (Windows 7), Tarjeta:"Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck, Disabled, None"

ESP8266_mqtt_relay_ADITYA:14: error: 'MQTT' does not name a type

 void callback(const MQTT::Publish& pub) {

```
                 ^
```

ESP8266_mqtt_relay_ADITYA:14: error: expected unqualified-id before '&' token

 void callback(const MQTT::Publish& pub) {

```
                              ^
```

ESP8266_mqtt_relay_ADITYA:14: error: expected ')' before '&' token

ESP8266_mqtt_relay_ADITYA:14: error: expected initializer before 'pub'

 void callback(const MQTT::Publish& pub) {

```
                                ^
```

ESP8266_mqtt_relay_ADITYA:14: error: 'MQTT' does not name a type

 void callback(const MQTT::Publish& pub) {

```
                 ^
```

ESP8266_mqtt_relay_ADITYA:14: error: expected unqualified-id before '&' token

 void callback(const MQTT::Publish& pub) {

```
                              ^
```

ESP8266_mqtt_relay_ADITYA:14: error: expected ')' before '&' token

ESP8266_mqtt_relay_ADITYA:14: error: expected initializer before 'pub'

 void callback(const MQTT::Publish& pub) {

```
                                ^
```

exit status 1
'MQTT' does not name a type

Este reporte podría tener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by AdySan** [comment]
I'm using this fork of the MQTT library, are you sure you're using this
too? https://github.com/Imroy/pubsubclient

**Comment by javiercviegas** [comment]
Aja. That was the problem , i just added it to arduino IDE and now it works. Thanks Ady!
