### ISSUE TITLE
How to change voice command and how to add accessory ?! 

### ISSUE THREAD

**Issue by khazaee** [AdySan/HomeKitLight#2]
hello my friend 
i want add accessory with custom button type in homekit and change voice command.

**Comment by AdySan** [comment]
Sorry Siri does not work for custom characteristics, only Apple characteristics.

**Comment by khazaee** [comment]
i want change adylight command

**Comment by AdySan** [comment]
Just change the name AdyLight to something else in the Light_accessory.js file
